; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ttgo-t-display]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = log2file, time, default
board_build.filesystem = littlefs
board_build.embed_files =
	lib/web/bootstrap.min.css.gz
	lib/web/bootstrap.min.js.gz
# test_build_src = yes
build_flags = 
	-std=gnu++17
	-D CORE_DEBUG_LEVEL=3
    -D UNITY_INCLUDE_PRINT_FORMATTED
    -D UNITY_OUTPUT_COLOR
	-D TTGO_T_DISPLAY
	-D TOUCH_CS=-1
	-D GPIO_BUTTON_TOP=35
    -D GPIO_BUTTON_BOTTOM=0
build_unflags = 
	-std=gnu++11
lib_deps = 
    throwtheswitch/Unity@^2.6.0
	bblanchon/ArduinoJson@^7.2.1
	mlesniew/PicoMQTT@^1.2.0
	bodmer/TFT_eSPI@^2.5.43

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = log2file, time, default
board_build.filesystem = littlefs
board_build.embed_files =
	lib/web/bootstrap.min.css.gz
	lib/web/bootstrap.min.js.gz
# test_build_src = yes
build_flags = 
	-std=gnu++17
	-D CORE_DEBUG_LEVEL=3
    -D UNITY_INCLUDE_PRINT_FORMATTED
    -D UNITY_OUTPUT_COLOR
build_unflags = 
	-std=gnu++11
lib_deps = 
    throwtheswitch/Unity@^2.6.0
	bblanchon/ArduinoJson@^7.2.1
	mlesniew/PicoMQTT@^1.2.0

[env:nodemcu]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_filters = log2file, time, default
board_build.filesystem = littlefs
board_build.embed_files =
	lib/web/bootstrap.min.css.gz
	lib/web/bootstrap.min.js.gz
# test_build_src = yes
build_flags = 
	-std=gnu++17
	-D ESP8266
	-D CORE_DEBUG_LEVEL=3
	-D UNITY_INCLUDE_PRINT_FORMATTED
	-D UNITY_OUTPUT_COLOR
    -fexceptions
build_unflags = 
	-std=gnu++11
lib_deps = 
	bblanchon/ArduinoJson@^7.2.1
	mlesniew/PicoMQTT@^1.2.0
